{
 "title": "smart-4",
 "description": "Smartmon Texfile node_exporter Dashboard\n\nExtends the following dashboard:\n\nhttps://grafana.com/dashboards/10530",
 "tags": [
  "prometheus",
  "node_exporter",
  "smartmon"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(smartmon_smartctl_version, instance)"
   },
   {
    "name": "device_model",
    "query": "label_values(smartmon_device_info, device_model)"
   },
   {
    "name": "disk",
    "query": "label_values(smartmon_device_info, disk)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<p></p>\n<p style=\"text-align: center;font-size: x-large;face:arial;\">__________ General Errors __________</p>"
  },
  {
   "title": "Read_Error_Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "smartmon_raw_read_error_rate_raw_value{ instance=~\"$instance\", disk=~\"$disk\" }",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Reallocate_Events",
   "type": "gauge",
   "description": "Number of reallocation events.\nCaused by read errors and broken sectors.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "smartmon_reallocated_event_count_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Pending_Sectors",
   "type": "gauge",
   "description": "Number of unstable sectors.\nCaused by read errors. \nWill possibly be remapped.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "smartmon_current_pending_sector_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Offline_Uncorrectable_Sectors",
   "type": "gauge",
   "description": "Number of uncorrectable sectors.\nDetected by a self-test (called offline scan)",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "smartmon_offline_uncorrectable_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "UDMA_CRC_Errors",
   "type": "gauge",
   "description": "Monitors connection quality between disk and motherboard.\nIndicates bad cable connection/cables.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "smartmon_udma_crc_error_count_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "content": "<p></p>\n<p style=\"text-align: center;font-size: x-large;face:arial;\">__________ HDD Specific Values __________</p>"
  },
  {
   "title": "Seek_Error_Rate",
   "type": "gauge",
   "description": "Errors during read action.\nPossible positioning problem of  read/write unit",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "smartmon_seek_error_rate_raw_value{ instance=~\"$instance\", disk=~\"$disk\" }",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Multi_Zone_Error_Rate",
   "type": "gauge",
   "description": "Errors during write",
   "gridPos": { "h": 4, "w": 8, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "smartmon_multi_zone_error_rate_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Spin_Retry_Count",
   "type": "gauge",
   "description": "Cont unsuccessful attempts to spin up to operational speed. \nCritical value indicating a mechanical problem of the motor.",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 12 },
   "targets": [
    {
     "expr": "smartmon_spin_retry_count_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  }
 ]
}