version: "3"

volumes:
    plex_data: {}

services:
    plex:
        image: linuxserver/plex
        container_name: plex
        hostname: plex
        restart: always

        volumes:
            - plex_data:/config
            - ./home:/etc/pihole/
        expose:
            - "80"
            - "443"
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp"
        cap_add:
            - NET_ADMIN
        dns:
            - 127.0.0.1
            - 1.1.1.1

        environment:
            - TZ=Europe/Moscow
            - ServerIP=192.168.1.49