version: "3"

volumes:
    plex_data: {}

services:
    plex:
        image: linuxserver/plex:version-1.20.2.3402-0fec14d92
        container_name: plex
        hostname: plex
        restart: unless-stopped

        volumes:
            - plex_data:/config
            - ./etc/media:/media

        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - VERSION=docker
