version: "3"

volumes:
    plex_data: {}

services:
    plex:
        image: linuxserver/plex:version-1.20.4.3517-ab5e1197c
        container_name: plex
        hostname: plex
        restart: unless-stopped

        volumes:
            - plex_data:/config
            - /mnt/md0/infra/plex/etc/music:/media/music
            - /mnt/md0/infra/plex/etc/video:/media/video

        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - VERSION=docker
