version: "3"

volumes:
    plex_data: {}

services:
    plex:
        image: linuxserver/plex
        container_name: plex
        hostname: plex
        restart: unless-stopped

        volumes:
            - plex_data:/config
            - ./etc/media:/media
        environment:
            - PUID=1000
            - PGID=1000
            - VERSION=docker

        ports:
            - "32400:32400/tcp"
