version: "3"

services:
    gitea_instance:
        image: gitea/gitea:1.12.5
        container_name: gitea_instance

        hostname: gitea_instance
        restart: always
        depends_on:
            - gitea_db

        env_file:
            - ./.env
        ports:
            - "222:22"
            - "3000:3000"

        volumes:
            - ./etc/gitea_instance/data:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
    gitea_db:
        image: mariadb:10
        container_name: gitea_db

        hostname: gitea_db
        restart: unless-stopped

        env_file:
            - ./.env

        volumes:
            - ./etc/gitea_db/data/:/var/lib/mysql
