version: "3"
services:
    wiki_db:
        image: postgres:13-alpine
        container_name: wiki_db

        hostname: wiki_db
        restart: unless-stopped

        logging:
            driver: "none"

        environment:
            POSTGRES_DB: wiki
            POSTGRES_USER: wikiuser
            POSTGRES_PASSWORD: wikipass

        volumes:
            - ./etc/db-data:/var/lib/postgresql/data
    wiki_instance:
        image: requarks/wiki:2.5
        container_name: wiki_instance

        hostname: wiki_instance
        restart: unless-stopped
        depends_on:
            - wiki_db

        environment:
            DB_TYPE: postgres
            DB_HOST: wiki_db
            DB_PORT: 5432
            DB_NAME: wiki
            DB_USER: wikiuser
            DB_PASS: wikipass

        ports:
            - "3008:3000"
