version: "3"
services:
    pihole:
        image: pihole/pihole:v5.1.2
        container_name: pihole
        hostname: pihole
        restart: always

        volumes:
            - ./etc/dnsmasq.d/:/etc/dnsmasq.d/
            - ./etc/pihole/:/etc/pihole/
        expose:
            - "80"
            - "443"
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp"
        cap_add:
            - NET_ADMIN
        dns:
            - 127.0.0.1
            - 1.1.1.1

        environment:
            - TZ=Europe/Moscow
            - ServerIP=192.168.1.49