version: "3"
services:
    nginx:
        image: umputun/nginx-le:1.3.0
        container_name: nginx
        hostname: nginx
        restart: always

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        volumes:
            - ./etc/nginx/.authfile:/etc/nginx/.authfile
            - ./etc/nginx/_nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx/_webdav.conf:/etc/nginx/service_webdav.conf
            - ./etc/nginx/gitea.conf:/etc/nginx/service_gitea.conf
            - ./etc/nginx/grafana_grafana.conf:/etc/nginx/service_grafana_grafana.conf
            - ./etc/nginx/grafana_nodeexporter.conf:/etc/nginx/service_grafana_nodeexporter.conf
            - ./etc/nginx/grafana_prometheus.conf:/etc/nginx/service_grafana_prometheus.conf
            - ./etc/nginx/keeweb.conf:/etc/nginx/service_keeweb.conf
            - ./etc/nginx/pihole.conf:/etc/nginx/service_pihole.conf
            - ./etc/nginx/plex.conf:/etc/nginx/service_plex.conf
            - ./etc/nginx/portainer.conf:/etc/nginx/service_portainer.conf
            - ./etc/nginx/wiki.conf:/etc/nginx/service_wiki.conf
            - ./etc/nginx/ssl:/etc/nginx/ssl
            - ./etc/nginx/webdav/data:/etc/nginx/webdav/data
            - ./etc/nginx/webdav/temp:/etc/nginx/webdav/temp
        ports:
            - "80:80"
            - "443:443"

        environment:
            - TZ=UTC
            - LETSENCRYPT=true
            - LE_EMAIL=fedy95@protonmail.com
            - LE_FQDN=gitea.fedy95.com,grafana.fedy95.com,keeweb.fedy95.com,nodeexporter.fedy95.com,pihole.fedy95.com,plex.fedy95.com,portainer.fedy95.com,prometheus.fedy95.com,webdav.fedy95.com,wiki.fedy95.com
