version: "3"
services:
    nginx:
        image: umputun/nginx-le:1.3.0
        container_name: nginx
        hostname: nginx
        restart: always

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        volumes:
            - ./etc/nginx/ssl:/etc/nginx/ssl
            - ./etc/nginx/service_trilium.conf:/etc/nginx/service_trilium.conf
        ports:
            - "80:80"
            - "443:443"

        environment:
            - TZ=UTC
            - LETSENCRYPT=true
            - LE_EMAIL=fedy95@protonmail.com
            - LE_FQDN=wiki.fedy95.com
