version: "3"

volumes:
    portainer_data: {}

services:
    portainer:
        image: portainer/portainer-ce:2.0.0
        hostname: portainer
        container_name: portainer
        restart: unless-stopped

        ports:
            - "3006:9000"
        volumes:
            - portainer_data:/data portainer/portainer-ce
            - /var/run/docker.sock:/var/run/docker.sock
