version: "3"

volumes:
    portainer_data: {}

services:
    portainer:
        image: portainer/portainer
        hostname: portainer
        container_name: portainer
        restart: unless-stopped

        expose:
            - "9000"
        volumes:
            - portainer_data:/data portainer/portainer
            - /var/run/docker.sock:/var/run/docker.sock
